define(['text!templates/html/overlay.html',
        'text!templates/html/ayuda_draw.html',
        'text!templates/html/creditos.html',
        'text!templates/html/metodologia.html',
        'text!templates/html/popup.html',
        'text!templates/html/popup_perc.html',
        'text!templates/html/popup_diff.html',
        'text!templates/html/telegramas.html',
        'text!templates/svg/referencias.html',
        'text!templates/sql/click_feature.txt',
        'text!templates/sql/draw_selection.txt',
        'text!templates/sql/permalink.txt',
        'text!templates/sql/cdb_crowdsource.txt',
        'text!templates/sql/cdb_telegrams.txt',
        'text!templates/sql/cdb_search.txt',
        'text!templates/sql/cdb_winner.txt',
        'text!templates/sql/cdb_party.txt',
        'text!templates/sql/cdb_hex_winner.txt',
        'text!templates/sql/cdb_hex_party.txt',
        'text!templates/sql/click_hex.txt',
        'text!templates/sql/hex_permalink.txt',
        'text!templates/sql/cdb_hex_test.txt',
        'text!templates/cartocss/perc.txt',
        'text!templates/cartocss/diff.txt',
        'text!templates/cartocss/hex_perc.txt',
        'text!templates/cartocss/hex_diff.txt'], 
        function(overlay_html, ayuda_draw_html, creditos_html, metodologia_html,
                 popup_html, popup_perc_html, popup_diff_html,
                 telegramas_html, referencias_svg,
                 click_feature_sql, draw_sql, permalink_sql,
                 cdb_crowdsource_sql, cdb_telegrams_sql, cdb_search_sql,
                 cdb_winner_sql, cdb_party_sql,
                 cdb_hex_winner_sql, cdb_hex_party_sql,
                 click_hex_sql, permalink_hex_sql, cdb_hex_test_sql,
                 perc_cartocss, diff_cartocss,
                 hex_perc_cartocss, hex_diff_cartocss) {
    
            return {
                //HTML
                overlay_html: overlay_html,
                ayuda_draw_html: ayuda_draw_html,
                creditos_html: creditos_html,
                metodologia_html: metodologia_html,
                popup_html: popup_html,
                popup_perc_html: popup_perc_html,
                popup_diff_html: popup_diff_html,
                telegramas_html: telegramas_html,
                //SVG
                referencias_svg: referencias_svg,
                //SQL
                click_feature_sql: click_feature_sql,
                click_hex_sql: click_hex_sql,
                draw_sql: draw_sql,
                permalink_sql: permalink_sql,
                search_sql: cdb_search_sql,
                cdb_winner_sql: cdb_winner_sql,
                cdb_party_sql: cdb_party_sql,
                cdb_hex_party_sql: cdb_hex_party_sql,
                cdb_hex_winner_sql: cdb_hex_winner_sql,
                permalink_hex_sql: permalink_hex_sql,
                cdb_hex_test_sql: cdb_hex_test_sql,
                cdb_crowdsource_sql: cdb_crowdsource_sql,
                cdb_telegrams_sql: cdb_telegrams_sql,
                //CARTOCSS
                perc_cartocss: perc_cartocss,
                diff_cartocss: diff_cartocss,
                hex_perc_cartocss: hex_perc_cartocss,
                hex_diff_cartocss: hex_diff_cartocss};
});